kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-provisioner
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-provisioner
    spec:
      serviceAccount: nfs-provisioner
      containers:
        - name: nfs-provisioner
          image: {{ .Values.nfs.provisionerimage }}
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: example.com/nfs
            - name: NFS_SERVER
              value: {{ .Values.nfs.ip }}
            - name: NFS_PATH
              value: {{ .Values.nfs.backuppath }}
      volumes:
        - name: nfs-client-root
          nfs:
            server: {{ .Values.nfs.ip }}
            path: {{ .Values.nfs.backuppath }}
